language: ruby
rvm:
- 2.0.0
- 1.9.3
script: bundle exec rake
branches:
  only:
  - gh-pages
  - /pages-(.*)/
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - CODECLIMATE_REPO_TOKEN=6c2897d7624992a7da96797c5e685ee3e0ee03c97321c4bd4c25bd4bb312f617
notifications:
  slack:
    secure: ghh3XlE14rh7yuLXviZv9r+9vOjwcAARYkmb+es8h0k57LWcqEGk7WEKtNY8QTYmIjeez7ne2mybqq85EhsgQRLiDBtRs7bsRFgFz6Q9iK+t1lslL0lLX8Ww1PuLA6ZM9bL8emsFSiJl3lBJYkU6Vpl8UH5z8awGAE9RAzDH/hw=
