url:
baseurl: ''

# Site settings
title: Submerge
email: submerge@stlchristian.edu
description: "An event designed to submerge High Schoolers DEEPER into CHOLLEGE//CITY//CHRIST."

# Color settings (hex-codes without the leading hash-tag)
color:
  #primary: fed136
  primary: 19a3ff
  #secondary: fec503  
  secondary: 1993ff
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Love the Lou
  pic: 1
  position: Service
  social:
    - title: twitter
      url: http://twitter.com/pursuitstl
    - title: facebook
      url: http://facebook.com/pursuitcommunities

- name: Jordan Howerton Band
  pic: 2
  position: Worship
  social:
    - title: twitter
      url: http://twitter.com/jordanhband
    - title: facebook
      url: http://facebook.com/jordanhowertonband

- name: Jon-Michael Brown
  pic: 3
  position: Preaching
  social:
    - title: twitter
      url: http://twitter.com/Jon_E_Mike
    - title: facebook
      url: http://www.facebook.com/jonmichael.d.brown

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/stlchristian
  - title: facebook
    url: http://facebook.com/stlchristian
  - title: google-plus
    url: http://plus.google.com/107642261577376969754
  - title: github
    url: http://github.com/stlchristian

# Postal address (add as many lines as necessary)
address:
  - line: 1360 Grandview Dr.
  - line: Florissant, MO 63033

# Build settings
markdown: kramdown
permalink: pretty
